# Generated by Django 4.2.15 on 2024-09-05 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewcount',
            old_name='ip_addres',
            new_name='ip_address',
        ),
    ]
